# Generated by Django 2.2.1 on 2020-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_doctordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Im_doctor',
            field=models.BooleanField(default=True),
        ),
    ]
