# Generated by Django 2.2.1 on 2020-03-17 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0007_doctor_im_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='doctorname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='result',
            field=models.CharField(default='dont know', max_length=20),
            preserve_default=False,
        ),
    ]
