# Generated by Django 2.2.1 on 2020-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200317_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
