# Generated by Django 2.2.1 on 2020-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_doctordetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
